/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author user
 */
public class homepage extends javax.swing.JFrame {

    /**
     * Creates new form homepage
     */
    public homepage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        customdetailsbutton = new javax.swing.JButton();
        invevtorybutton = new javax.swing.JButton();
        orderdetailsbutton = new javax.swing.JButton();
        paymentbutton = new javax.swing.JButton();
        employeesbutton = new javax.swing.JButton();
        reportsbutton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        suppliersbutton = new javax.swing.JButton();
        logoutbutton = new javax.swing.JButton();
        userregbutton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("HOME PAGE");
        setPreferredSize(new java.awt.Dimension(1366, 768));

        customdetailsbutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        customdetailsbutton.setText("Customer Details");
        customdetailsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customdetailsbuttonActionPerformed(evt);
            }
        });

        invevtorybutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        invevtorybutton.setText("Inventory ");
        invevtorybutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                invevtorybuttonActionPerformed(evt);
            }
        });

        orderdetailsbutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        orderdetailsbutton.setText("Order Details");
        orderdetailsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                orderdetailsbuttonActionPerformed(evt);
            }
        });

        paymentbutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        paymentbutton.setText("Payments ");
        paymentbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymentbuttonActionPerformed(evt);
            }
        });

        employeesbutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        employeesbutton.setText("Employees");
        employeesbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                employeesbuttonActionPerformed(evt);
            }
        });

        reportsbutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        reportsbutton.setText("Reports");
        reportsbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reportsbuttonActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon("D:\\Academic\\IMGT 3+34\\unique-construction-and-transport-13304-cover.png")); // NOI18N

        suppliersbutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        suppliersbutton.setText("Suppliers");
        suppliersbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                suppliersbuttonActionPerformed(evt);
            }
        });

        logoutbutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        logoutbutton.setText("Log Out");
        logoutbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutbuttonActionPerformed(evt);
            }
        });

        userregbutton.setFont(new java.awt.Font("Times New Roman", 1, 20)); // NOI18N
        userregbutton.setText("User Registratiion");
        userregbutton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                userregbuttonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 387, Short.MAX_VALUE)
        );

        jLabel2.setIcon(new javax.swing.ImageIcon("D:\\Academic\\IMGT 3+34\\Ek3C.gif")); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(102, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(0, 92, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(invevtorybutton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(reportsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(userregbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(customdetailsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(orderdetailsbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(paymentbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(employeesbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(suppliersbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(logoutbutton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 639, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(76, 76, 76))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(invevtorybutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(customdetailsbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(orderdetailsbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(paymentbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(employeesbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(suppliersbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(reportsbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(userregbutton)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(logoutbutton)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 406, Short.MAX_VALUE)
                        .addGap(31, 31, 31))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void customdetailsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customdetailsbuttonActionPerformed
        customerdetails h=new customerdetails();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_customdetailsbuttonActionPerformed

    private void invevtorybuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_invevtorybuttonActionPerformed
        inventorydetails h=new inventorydetails();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_invevtorybuttonActionPerformed

    private void orderdetailsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_orderdetailsbuttonActionPerformed
        Purchasedetails h=new Purchasedetails();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_orderdetailsbuttonActionPerformed

    private void paymentbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymentbuttonActionPerformed
        customerpayment h=new customerpayment();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_paymentbuttonActionPerformed

    private void employeesbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_employeesbuttonActionPerformed
        Employeedetails h=new Employeedetails();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_employeesbuttonActionPerformed

    private void suppliersbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_suppliersbuttonActionPerformed
        supplierdetails h=new supplierdetails();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_suppliersbuttonActionPerformed

    private void reportsbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reportsbuttonActionPerformed
        Reports h=new Reports();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_reportsbuttonActionPerformed

    private void logoutbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutbuttonActionPerformed
        welcome h=new welcome();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_logoutbuttonActionPerformed

    private void userregbuttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_userregbuttonActionPerformed
        Employeedetails h=new Employeedetails();
        h.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_userregbuttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(homepage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new homepage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton customdetailsbutton;
    private javax.swing.JButton employeesbutton;
    private javax.swing.JButton invevtorybutton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoutbutton;
    private javax.swing.JButton orderdetailsbutton;
    private javax.swing.JButton paymentbutton;
    private javax.swing.JButton reportsbutton;
    private javax.swing.JButton suppliersbutton;
    private javax.swing.JButton userregbutton;
    // End of variables declaration//GEN-END:variables
}
