
import DTO.PurchaseAddViewDTO;
import DTO.PurchaseDetailsDTO;
import Dao.PurchaseDetailsDao;
import java.sql.SQLException;
import java.text.ParseException;
import java.util.Date;
import java.util.Iterator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
/**
 *
 * @author user
 */
public class Purchasedetails extends javax.swing.JFrame {

    /**
     * Creates new form Purchasedetails
     */
    PurchaseDetailsDTO purchase = new PurchaseDetailsDTO();
    PurchaseDetailsDao purchaseDetails = new PurchaseDetailsDao();

    public Purchasedetails() {
        initComponents();
        getCustomerAndItemDetails();
        generateId();
        loadPurchaseDetails();
        loadHoldPurchaseDetails();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        availableoutsCheckbox = new java.awt.Checkbox();
        jLabel6 = new javax.swing.JLabel();
        ordernoField = new javax.swing.JTextField();
        holdButton = new javax.swing.JButton();
        dateField = new com.toedter.calendar.JDateChooser();
        jPanel5 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        unitpriceField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        quantityField = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        netamountFeild = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        addButton = new javax.swing.JButton();
        okButton = new javax.swing.JButton();
        duedate = new com.toedter.calendar.JDateChooser();
        itemIdCombo = new javax.swing.JComboBox<>();
        itemNameCombo = new javax.swing.JComboBox<>();
        customerIdComboBox1 = new javax.swing.JComboBox<>();
        customerNameCombo = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        placedordtable = new javax.swing.JTable();
        jTextField8 = new javax.swing.JTextField();
        dateRadbutton = new javax.swing.JRadioButton();
        ordnoRadbutton = new javax.swing.JRadioButton();
        custIDradButton = new javax.swing.JRadioButton();
        searchButtn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        holdordTable = new javax.swing.JTable();
        searchButton = new javax.swing.JButton();
        searchField = new javax.swing.JTextField();
        dateradioButton = new javax.swing.JRadioButton();
        ordnoRAdBut = new javax.swing.JRadioButton();
        custIDradbutton = new javax.swing.JRadioButton();
        backButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("ORDER DETAILS");

        jTabbedPane1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel1.setText("Customer ID");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel2.setText("Customer Name");

        jLabel4.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel4.setText("Date");

        availableoutsCheckbox.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        availableoutsCheckbox.setLabel("Available Outstanding");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel6.setText("Order No");

        holdButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        holdButton.setText("Hold");
        holdButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                holdButtonActionPerformed(evt);
            }
        });

        jPanel5.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel9.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel9.setText("Item ID");

        jLabel7.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel7.setText("Item Name");

        jLabel10.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel10.setText("Unit Price (Rs)");

        unitpriceField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unitpriceFieldActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel11.setText("Quantity");

        jLabel12.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel12.setText("Net Amount (Rs)");

        netamountFeild.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                netamountFeildActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        jLabel13.setText("Due Date");

        addButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        addButton.setText("ADD");

        okButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        itemIdCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        itemIdCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemIdComboActionPerformed(evt);
            }
        });

        itemNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        itemNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                itemNameComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(netamountFeild)
                            .addComponent(duedate, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE))
                        .addGap(0, 63, Short.MAX_VALUE))
                    .addGroup(jPanel5Layout.createSequentialGroup()
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel7)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(unitpriceField)
                            .addComponent(quantityField, javax.swing.GroupLayout.DEFAULT_SIZE, 207, Short.MAX_VALUE)
                            .addComponent(itemIdCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(itemNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(addButton)
                    .addComponent(okButton))
                .addContainerGap(40, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(addButton)
                    .addComponent(itemIdCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(itemNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(unitpriceField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(quantityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(netamountFeild, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel13)
                        .addComponent(okButton))
                    .addComponent(duedate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        customerIdComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerIdComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerIdComboBox1ActionPerformed(evt);
            }
        });

        customerNameCombo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        customerNameCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                customerNameComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(69, 69, 69)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(availableoutsCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(holdButton))
                            .addComponent(dateField, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerIdComboBox1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(customerNameCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(55, 55, 55)
                        .addComponent(jLabel6)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordernoField, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(ordernoField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(customerIdComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(customerNameCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel4)
                    .addComponent(dateField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(availableoutsCheckbox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(holdButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jLabel8.setIcon(new javax.swing.ImageIcon("D:\\Academic\\IMGT 3+34\\orders.jpg")); // NOI18N
        jLabel8.setText("jLabel8");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(61, 61, 61)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 279, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(26, 26, 26))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Add an order", jPanel1);

        placedordtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No ", "Customer Name", "Item ID", "Item Name", "Unit Price(Rs)", "Quantity", "Net Amount", "order Placed Date", "Payment Due Date"
            }
        ));
        jScrollPane1.setViewportView(placedordtable);

        jTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField8ActionPerformed(evt);
            }
        });

        dateRadbutton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateRadbutton.setText("Date");

        ordnoRadbutton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ordnoRadbutton.setText("Order No");

        custIDradButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        custIDradButton.setText("Customer ID");
        custIDradButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                custIDradButtonActionPerformed(evt);
            }
        });

        searchButtn.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchButtn.setText("Search");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(custIDradButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(ordnoRadbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(dateRadbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(searchButtn, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(dateRadbutton)
                    .addComponent(ordnoRadbutton)
                    .addComponent(custIDradButton)
                    .addComponent(searchButtn)
                    .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 269, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(37, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View of Placed Orders", jPanel3);

        holdordTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Order No", "Customer Name", "Item ID", "Item Name", "Unit Price(Rs)", "Quantity", "Net Amount", "Order Placed Date"
            }
        ));
        jScrollPane2.setViewportView(holdordTable);

        searchButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        searchButton.setText("Search");

        searchField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchFieldActionPerformed(evt);
            }
        });

        dateradioButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        dateradioButton.setText("Date");

        ordnoRAdBut.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        ordnoRAdBut.setText("Order No");

        custIDradbutton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        custIDradbutton.setText("Customer ID");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 967, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(custIDradbutton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ordnoRAdBut)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(dateradioButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchButton)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(searchButton)
                    .addComponent(searchField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dateradioButton)
                    .addComponent(ordnoRAdBut)
                    .addComponent(custIDradbutton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 263, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(48, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("View of Hold Orders", jPanel4);

        backButton.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        backButton.setText("Back");
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(backButton, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(78, 78, 78))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(backButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane1)
                .addGap(22, 22, 22))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        homepage h = new homepage();
        h.setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void jTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField8ActionPerformed

    private void holdButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_holdButtonActionPerformed
        hold h = new hold();
        h.setVisible(true);
    }//GEN-LAST:event_holdButtonActionPerformed

    private void searchFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchFieldActionPerformed

    private void custIDradButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_custIDradButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_custIDradButtonActionPerformed

    private void unitpriceFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unitpriceFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_unitpriceFieldActionPerformed

    private void netamountFeildActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_netamountFeildActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_netamountFeildActionPerformed

    private void customerNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerNameComboActionPerformed
        getCustomerIdByCustomerName();        // TODO add your handling code here:
    }//GEN-LAST:event_customerNameComboActionPerformed

    private void customerIdComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_customerIdComboBox1ActionPerformed
        getCustomerNameByCustomerId();
        // TODO add your handling code here:
    }//GEN-LAST:event_customerIdComboBox1ActionPerformed

    private void itemIdComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemIdComboActionPerformed
        getItemNameByItemId();        // TODO add your handling code here:
    }//GEN-LAST:event_itemIdComboActionPerformed

    private void itemNameComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_itemNameComboActionPerformed
        // TODO add your handling code here:
        getItemIdByItemName();
    }//GEN-LAST:event_itemNameComboActionPerformed

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        SubmitPurchaseDetailAdd();
        // TODO add your handling code here:
    }//GEN-LAST:event_okButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Purchasedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Purchasedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Purchasedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Purchasedetails.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Purchasedetails().setVisible(true);
            }
        });
    }

    public void getCustomerAndItemDetails() {

        purchase = purchaseDetails.getPurchaseDetails();

        // Add inventory item, category doenot exist
        DefaultComboBoxModel customerIdModel = new DefaultComboBoxModel(purchase.customerDetails.customerIds.toArray());
        customerIdComboBox1.setModel(customerIdModel);
        DefaultComboBoxModel CustomerNameModel = new DefaultComboBoxModel(purchase.customerDetails.customerNames.toArray());
        customerNameCombo.setModel(CustomerNameModel);

        DefaultComboBoxModel itemIdModel = new DefaultComboBoxModel(purchase.itemDetails.itemIds.toArray());
        itemIdCombo.setModel(itemIdModel);
        DefaultComboBoxModel itemNameModel = new DefaultComboBoxModel(purchase.itemDetails.itemNames.toArray());
        itemNameCombo.setModel(itemNameModel);
    }

    public void getItemNameByItemId() {

        String itemId = (String) itemIdCombo.getSelectedItem();
        String nameToBeSet = FindItemNameById(itemId);
        itemNameCombo.setSelectedItem(nameToBeSet);

    }

    public void getItemIdByItemName() {

        String itemName = (String) itemNameCombo.getSelectedItem();
        String idToBeSet = FindItemIdByName(itemName);
        itemIdCombo.setSelectedItem(idToBeSet);

    }

    public String FindItemNameById(String searchId) {
        String Name = "";
        for (int i = 0; i < purchase.itemDetails.itemDetails.size(); i++) {
            List a = (List) purchase.itemDetails.itemDetails.get(i);
            String id = a.get(0).toString();
            if (searchId.equals(id)) {
                Name = a.get(1).toString();
            }
        }
        return Name;
    }

    public String FindItemIdByName(String searchName) {
        String Id = "";
        for (int i = 0; i < purchase.itemDetails.itemDetails.size(); i++) {
            List a = (List) purchase.itemDetails.itemDetails.get(i);
            String name = a.get(1).toString();
            if (searchName.equals(name)) {
                Id = a.get(0).toString();
            }
        }
        return Id;
    }

    public void getCustomerNameByCustomerId() {

        String customerId = (String) customerIdComboBox1.getSelectedItem();
        String nameToBeSet = FindCustomerNameById(customerId);
        customerNameCombo.setSelectedItem(nameToBeSet);

    }

    public void getCustomerIdByCustomerName() {

        String itemName = (String) customerNameCombo.getSelectedItem();
        String idToBeSet = FindCustomerIdByName(itemName);
        customerIdComboBox1.setSelectedItem(idToBeSet);

    }

    public String FindCustomerNameById(String searchId) {
        String Name = "";
        for (int i = 0; i < purchase.customerDetails.customerDetails.size(); i++) {
            List a = (List) purchase.customerDetails.customerDetails.get(i);
            String id = a.get(0).toString();
            if (searchId.equals(id)) {
                Name = a.get(1).toString();
            }
        }
        return Name;
    }

    public String FindCustomerIdByName(String searchName) {
        String Id = "";
        for (int i = 0; i < purchase.customerDetails.customerDetails.size(); i++) {
            List a = (List) purchase.customerDetails.customerDetails.get(i);
            String name = a.get(1).toString();
            if (searchName.equals(name)) {
                Id = a.get(0).toString();
            }
        }
        return Id;
    }

    public void generateId() {

        String id = purchaseDetails.nextOrderId();
        ordernoField.setText(id);
    }

    public void SubmitPurchaseDetailAdd() {
        int isOutStanding = 0;
        String customerId = (String) customerIdComboBox1.getSelectedItem();

        String customerName = (String) customerNameCombo.getSelectedItem();
        Date orderedDate = dateField.getDate();

        Boolean result = availableoutsCheckbox.getState();
        if (result == true) {
            isOutStanding = 1;
        }
        int quantity = Integer.parseInt(quantityField.getText());
        Double unitPrice = Double.parseDouble(unitpriceField.getText());
        Date itemAddedDate = duedate.getDate();
        String itemId = (String) itemIdCombo.getSelectedItem();
        String itemName = (String) itemNameCombo.getSelectedItem();
        String purchaseId = ordernoField.getText();
        Double paymentReceivable = Double.parseDouble(netamountFeild.getText());

        PurchaseAddViewDTO purchaseItem = new PurchaseAddViewDTO();
        purchaseItem.setPurchaseId(purchaseId);
        purchaseItem.setCustomerId(customerId);
        purchaseItem.setDueDate(orderedDate);
        purchaseItem.setIsOutStanding(isOutStanding);
        purchaseItem.setItemId(itemId);
        purchaseItem.setOrderedDate(orderedDate);
        purchaseItem.setReceivableAmount(paymentReceivable);
        purchaseItem.setSoldQuantity(quantity);
        purchaseItem.setUnitValue(unitPrice);
        purchaseItem.setCustomerName(customerName);
        purchaseItem.setItemName(itemName);

        try {
            boolean res = purchaseDetails.addNewInventory(purchaseItem);
            if (res == true) {
                JOptionPane.showMessageDialog(this, "Order added sucessfully");
                //ClearFields();
                loadPurchaseDetails();
                generateId();
            } else {
                JOptionPane.showMessageDialog(this, "Error occur in adding Order");
            }
        } catch (SQLException ex) {
            Logger.getLogger(Employeedetails.class.getName()).log(Level.SEVERE, null, ex);
        } catch (ParseException ex) {
            Logger.getLogger(Employeedetails.class.getName()).log(Level.SEVERE, null, ex);
        }

    }

    public void loadPurchaseDetails() {

        List<List<String>> res = purchaseDetails.ViewPurchaseDetails();
        addRowToJTable(res);
    }

    public void addRowToJTable(List res) {
        placedordtable.setShowGrid(true);
        DefaultTableModel model = (DefaultTableModel) placedordtable.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[9];
        for (Iterator it = res.iterator(); it.hasNext();) {
            List<String> innerList = (List<String>) it.next();
            rowData[0] = innerList.get(0);
            rowData[1] = innerList.get(1);
            rowData[2] = innerList.get(2);
            rowData[3] = innerList.get(3);
            rowData[4] = innerList.get(4);
            rowData[5] = innerList.get(5);
            rowData[6] = innerList.get(6);
            rowData[7] = innerList.get(7);
            rowData[8] = innerList.get(8);
            

            model.addRow(rowData);

        }
    }
    
     public void loadHoldPurchaseDetails() {

        List<List<String>> res = purchaseDetails.ViewHoldPurchaseDetails();
        addRowToJTableHold(res);
    }

    public void addRowToJTableHold(List res) {
        holdordTable.setShowGrid(true);
        DefaultTableModel model = (DefaultTableModel) holdordTable.getModel();
        model.setRowCount(0);
        Object rowData[] = new Object[8];
        for (Iterator it = res.iterator(); it.hasNext();) {
            List<String> innerList = (List<String>) it.next();
            rowData[0] = innerList.get(0);
            rowData[1] = innerList.get(1);
            rowData[2] = innerList.get(2);
            rowData[3] = innerList.get(3);
            rowData[4] = innerList.get(4);
            rowData[5] = innerList.get(5);
            rowData[6] = innerList.get(6);
            rowData[7] = innerList.get(7);
           

            model.addRow(rowData);

        }
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addButton;
    private java.awt.Checkbox availableoutsCheckbox;
    private javax.swing.JButton backButton;
    private javax.swing.JRadioButton custIDradButton;
    private javax.swing.JRadioButton custIDradbutton;
    private javax.swing.JComboBox<String> customerIdComboBox1;
    private javax.swing.JComboBox<String> customerNameCombo;
    private com.toedter.calendar.JDateChooser dateField;
    private javax.swing.JRadioButton dateRadbutton;
    private javax.swing.JRadioButton dateradioButton;
    private com.toedter.calendar.JDateChooser duedate;
    private javax.swing.JButton holdButton;
    private javax.swing.JTable holdordTable;
    private javax.swing.JComboBox<String> itemIdCombo;
    private javax.swing.JComboBox<String> itemNameCombo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JTextField netamountFeild;
    private javax.swing.JButton okButton;
    private javax.swing.JTextField ordernoField;
    private javax.swing.JRadioButton ordnoRAdBut;
    private javax.swing.JRadioButton ordnoRadbutton;
    private javax.swing.JTable placedordtable;
    private javax.swing.JTextField quantityField;
    private javax.swing.JButton searchButtn;
    private javax.swing.JButton searchButton;
    private javax.swing.JTextField searchField;
    private javax.swing.JTextField unitpriceField;
    // End of variables declaration//GEN-END:variables
}
